[[d1_databases]]
binding = "DB"
database_name = "project2026"
database_id = "486a143f-a52e-4c62-a325-5c03df096d0b"
migrations_dir = "migrations"
compatibility_date = "2025-12-19"
pages_build_output_dir = ".next"