#:schema node_modules/wrangler/config-schema.json
name = "cicd-betterauth-project"
pages_build_output_dir = ".vercel/output/static"
compatibility_date = "2024-11-18"

[[d1_databases]]
binding = "DB"
database_name = "project2026"
database_id = "486a143f-a52e-4c62-a325-5c03df096d0b"
migrations_dir = "migrations"